title: DAVID DONG 的博客
author: David Dong
email: dqdongg@hotmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is DavidDong's blog. Welcome!
  
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
minimal:
  name: David Dong
  tagline: Java/C/C#/Python
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    wechat: 
    github:  gangdong
    linkedIn: in/thelehhman
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minimal

#minimal:
#  disqus_shortname: games
#minimal:
#  navigation:
#    - title: My Work
#      url: "/my-work"
#    - title: Resume
#      url: "/resume"

plugins:
  - jekyll-seo-tag
#  - jekyll-feed